#!/bin/zsh

RED="\033[0;31m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
YELLOW="\033[1;33m"
NC="\033[0m"

email="okitkowski114@gmail.com"
ssh_config_value="Host github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519"

# BREW
echo "${YELLOW}========== INSTALLING BREW REQUIREMENTS ==========${NC}"
xargs -t -I {} brew install {} < brew-requirements.txt
echo "\n"

echo "${YELLOW}========== INSTALLING CASKS ==========${NC}"
xargs -t -I {} brew install --cask {} < brew-casks.txt
echo "\n"

# GIT
echo "${YELLOW}========== SETTING UP GIT ==========${NC}"
git config --global user.name kitkovsky
git config --global user.email "$email"

ssh-keygen -t ed25519 -C "$email"
eval "$(ssh-agent -s)"

touch ~/.ssh/config
echo "$ssh_config_value" > ~/.ssh/config

ssh-add --apple-use-keychain ~/.ssh/id_ed25519
pbcopy < ~/.ssh/id_ed25519.pub

echo "${BLUE}=========="
echo "The ssh public key has been copied to your clipboard, finish adding it to your GitHub account here:"
echo "https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account"
echo "Press Enter to continue..."
echo "==========${NC}"
read

echo "\n"

# OH-MY-ZSH
echo "${YELLOW}========== OH-MY-ZSH ==========${NC}"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k

# FONTS
echo "${YELLOW}========== FONTS ==========${NC}"
cd ~/Library/Fonts
wget -i ./fonts-list.txt
cd -

# STOWING DOTFILES
echo "${YELLOW}========== STOWING DOTFILES ==========${NC}"
rm ~/.zshrc
stow --target=${HOME} */

# NEOVIM
echo "${YELLOW}========== INSTALLING PACKER ==========${NC}"
git clone --depth 1 https://github.com/wbthomason/packer.nvim  ~/.local/share/nvim/site/pack/packer/start/packer.nvim

# RUST
echo "${YELLOW}========== INSTALLING CARGO ==========${NC}"
curl https://sh.rustup.rs -sSf | sh

# DEFAULTS
echo "${YELLOW}========== WRITING DEFAULTS ==========${NC}"
defaults write com.apple.Dock autohide-delay -float 0
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
defaults write com.googlecode.iterm2 PrefsCustomFolder -string "~/.dotfiles-mac/iterm2/.config/iterm2"
defaults write com.amethyst.Amethyst floating \
'(
        {
        id = "com.googlecode.iterm2";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.Safari";
        "window-titles" =         (
        );
    },
        {
        id = "com.spotify.client";
        "window-titles" =         (
        );
    },
        {
        id = "com.google.Chrome";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.Photos";
        "window-titles" =         (
        );
    },
        {
        id = "com.apple.mail";
        "window-titles" =         (
        );
    }
)'

for app in "Dock" "Amethyst" "iTerm2"; do
  killall "${app}" > /dev/null 2>&1
done

echo "${GREEN}========== ALL DONE ==========${NC}"
echo "Finish the setup by setting system preferences from here: https://drive.google.com/file/d/1OOL6S6Mq6pkmsiN-yq6Da6Na-vGXlOAs/view?usp=sharing"
