#!/bin/zsh

RED="\033[0;31m"
GREEN="\033[0;32m"
BLUE="\033[0;34m"
YELLOW="\033[1;33m"
NC="\033[0m"

email="okitkowski114@gmail.com"
ssh_config_value="Host github.com
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/id_ed25519"

if [[ $(csrutil status) != *"disabled"* ]]; then
  echo "${RED}========== DISABLE SIP TO CONTINUE, EXITING ==========${NC}"
  exit -1
fi

# BREW
echo "${YELLOW}========== INSTALLING BREW REQUIREMENTS ==========${NC}"
brew tap oven-sh/bun
xargs -t -I {} brew install {} < brew-requirements.txt
echo "\n"

echo "${YELLOW}========== INSTALLING CASKS ==========${NC}"
xargs -t -I {} brew install --cask {} < brew-casks.txt
echo "\n"

# GIT
echo "${YELLOW}========== SETTING UP GIT ==========${NC}"
git config --global user.name kitkovsky
git config --global user.email "$email"
git config --global --add --bool push.autoSetupRemote true
git config --global pager.branch false

ssh-keygen -t ed25519 -C "$email"
eval "$(ssh-agent -s)"

touch ~/.ssh/config
echo "$ssh_config_value" > ~/.ssh/config

ssh-add --apple-use-keychain ~/.ssh/id_ed25519
pbcopy < ~/.ssh/id_ed25519.pub

echo "${BLUE}=========="
echo "The ssh public key has been copied to your clipboard, finish by adding it to your GitHub account here:"
echo "https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account"
echo "Press Enter to continue..."
echo "==========${NC}"
read

echo "\n"

# FONTS
echo "${YELLOW}========== FONTS ==========${NC}"
cd ~/Library/Fonts
wget -i ~/.dotfiles-mac/fonts-list.txt
cd -

# YABAI
echo "${YELLOW}========== CONFIGURING YABAI ==========${NC}"
sudo nvram boot-args=-arm64e_preview_abi
echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai)) --load-sa" | sudo tee /private/etc/sudoers.d/yabai
echo "\n"

# STOWING DOTFILES
echo "${YELLOW}========== STOWING DOTFILES ==========${NC}"
stow --target=${HOME} */

# RUST
echo "${YELLOW}========== INSTALLING CARGO ==========${NC}"
curl https://sh.rustup.rs -sSf | sh

# TPM
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# DEFAULTS
echo "${YELLOW}========== WRITING DEFAULTS ==========${NC}"
defaults write com.apple.Dock autohide-delay -float 0
defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
defaults write com.googlecode.iterm2 PrefsCustomFolder -string "~/.dotfiles-mac/iterm2/.config/iterm2"

killall Dock > /dev/null 2>&1

# OH-MY-ZSH
echo "${YELLOW}========== OH-MY-ZSH ==========${NC}"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
